version: '2'
services:
  spring:
    image: your-spring-app-image  # Spring uygulaman覺z覺n Docker imaj覺n覺 buraya ekleyin
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-server:9092
    ports:
      - "9000:9000"
    networks:
      - kafka-network
  kafka-server:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    depends_on:
      - zookeeper-server
    networks:
      - kafka-network
  zookeeper-server:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - kafka-network

networks:
  kafka-network:
    external:
      name: kafka-network
